### ISSUE TITLE
Unresolved reference setupWithNavController

### ISSUE THREAD

**Issue by YesayaSoftware** [ResoCoder/forecast-mvvm-android-kotlin#2]
![image](https://user-images.githubusercontent.com/18540067/49142388-b2833a80-f309-11e8-9a7e-e3701dc8c6e8.png)

**Comment by linucksrox** [comment]
Do you have this import statement?
`import androidx.navigation.ui.setupWithNavController`

**Comment by YesayaSoftware** [comment]
I did @linucksrox, but it show like it is unused.

**Comment by linucksrox** [comment]
Can you post the entire MainActivity.kt file? Also did you add the proper kotlin extensions in the project's build.gradle file, and add the correct dependencies in the app build.gradle file?
I just got everything working in my environment today by using the dependencies used here: https://github.com/ResoCoder/forecast-mvvm-android-kotlin/commit/f4434b47c2530e2e0fffaac9e0f1ecd36c6ff402

The exact versions are important too, it's not always safe to assume you should use newer dependency versions just because they are available.

**Comment by YesayaSoftware** [comment]
`package software.yesaya.weather.ui

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import androidx.navigation.NavController
import androidx.navigation.Navigation
import androidx.navigation.ui.NavigationUI
import androidx.navigation.ui.setupWithNavController
import kotlinx.android.synthetic.main.activity_main.*
import software.yesaya.weather.R

class MainActivity : AppCompatActivity() {

    private lateinit var navController: NavController

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        setSupportActionBar(toolbar)

        navController = Navigation.findNavController(this, R.id.nav_host_fragment)

        bottom_nav.setupWithNavController(navController)

        NavigationUI.setupActionBarWithNavController(this, navController)
    }

    override fun onSupportNavigateUp(): Boolean {
        return NavigationUI.navigateUp(null, navController)
    }
}
`

**Comment by YesayaSoftware** [comment]
Thanks @linucksrox , I double check each file and Rebuild the project then Invalidate Caches/Restart. Now am good to go. Thanks

**Comment by masokaya** [comment]
use this method, it worked for me
 val navController = findNavController( this,R.id.nav_host_fragment)
 val navView: NavigationView = findViewById(R.id.nav_view)
        setupWithNavController(navView,navController)

**Comment by divyansh1004** [comment]
Hi,
I m getting the same issue.
